In [1]:
import pandas as pd

# Creating a sample dataset for Experiment 2
data = {
    'EmpID': [101, 102, 103, 104, 105, 106],
    'Name': ['Arun', 'Bala', 'Divya', 'Priya', 'Ravi', 'Karthik'],
    'Department': ['HR', 'IT', 'CSE', 'AI&DS', 'IT', 'AI&DS'],
    'Salary': [25000, 30000, 45000, 38000, 32000, 41000],
    'Experience_Years': [2, 3, 7, 5, 4, 6]
}

# Save as CSV file
df_initial = pd.DataFrame(data)
df_initial.to_csv('employee_salaries.csv', index=False)
print("Dataset 'employee_salaries.csv' successfully created!")

Dataset 'employee_salaries.csv' successfully created!

In [2]:
import pandas as pd

# Dataset Name: employee_salaries.csv
dataset_name = 'employee_salaries.csv'

# Program 1: Reading CSV File
df = pd.read_csv(dataset_name)

# Program 2: Display First Five Records
print("--- First 5 Records ---")
display(df.head())

# Program 3: Display Dataset Information
print("\n--- Dataset Information ---")
df.info()

# Program 4: Statistical Summary
print("\n--- Statistical Summary ---")
display(df.describe())

--- First 5 Records ---

   EmpID   Name Department  Salary  Experience_Years
0    101   Arun         HR   25000                 2
1    102   Bala         IT   30000                 3
2    103  Divya        CSE   45000                 7
3    104  Priya      AI&DS   38000                 5
4    105   Ravi         IT   32000                 4

--- Dataset Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmpID             6 non-null      int64
 1   Name              6 non-null      object
 2   Department        6 non-null      object
 3   Salary            6 non-null      int64
 4   Experience_Years  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

--- Statistical Summary ---

            EmpID        Salary  Experience_Years
count    6.000000      6.000000          6.000000
mean   103.500000  35166.666667          4.500000
std      1.870829   7467.708261          1.870829
min    101.000000  25000.000000          2.000000
25%    102.250000  30500.000000          3.250000
50%    103.500000  35000.000000          4.500000
75%    104.750000  40250.000000          5.750000
max    106.000000  45000.000000          7.000000

In [3]:
# Program 8: Export to CSV
df.to_csv('output_employee.csv', index=False)
print("CSV File Exported successfully: output_employee.csv")

# Program 9: Export to Excel
df.to_excel('output_employee.xlsx', index=False)
print("Excel File Exported successfully: output_employee.xlsx")

# Program 10: Export to JSON
df.to_json('output_employee.json')
print("JSON File Exported successfully: output_employee.json")

CSV File Exported successfully: output_employee.csv
Excel File Exported successfully: output_employee.xlsx
JSON File Exported successfully: output_employee.json

In [4]:
import pandas as pd

# 1. Importing dataset from CSV file
dataset_path = 'employee_salaries.csv'
df = pd.read_csv(dataset_path)

print("==========================================")
print(" 1. DISPLAYING FIRST 5 RECORDS (df.head()) ")
print("==========================================")
display(df.head())

print("\n==========================================")
print(" 2. DISPLAYING LAST 5 RECORDS (df.tail())  ")
print("==========================================")
display(df.tail())

print("\n==========================================")
print(" 3. DATASET INFORMATION (df.info())       ")
print("==========================================")
df.info()

print("\n==========================================")
print(" 4. DATASET SHAPE AND COLUMN NAMES        ")
print("==========================================")
print("Shape (Rows, Columns):", df.shape)
print("Column Names:", list(df.columns))

print("\n==========================================")
print(" 5. DESCRIPTIVE STATISTICAL SUMMARY       ")
print("==========================================")
display(df.describe())

==========================================
 1. DISPLAYING FIRST 5 RECORDS (df.head())
==========================================

   EmpID   Name Department  Salary  Experience_Years
0    101   Arun         HR   25000                 2
1    102   Bala         IT   30000                 3
2    103  Divya        CSE   45000                 7
3    104  Priya      AI&DS   38000                 5
4    105   Ravi         IT   32000                 4

==========================================
 2. DISPLAYING LAST 5 RECORDS (df.tail())
==========================================

   EmpID     Name Department  Salary  Experience_Years
1    102     Bala         IT   30000                 3
2    103    Divya        CSE   45000                 7
3    104    Priya      AI&DS   38000                 5
4    105     Ravi         IT   32000                 4
5    106  Karthik      AI&DS   41000                 6

==========================================
 3. DATASET INFORMATION (df.info())
==========================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EmpID             6 non-null      int64
 1   Name              6 non-null      object
 2   Department        6 non-null      object
 3   Salary            6 non-null      int64
 4   Experience_Years  6 non-null      int64
dtypes: int64(3), object(2)
memory usage: 372.0+ bytes

==========================================
 4. DATASET SHAPE AND COLUMN NAMES
==========================================
Shape (Rows, Columns): (6, 5)
Column Names: ['EmpID', 'Name', 'Department', 'Salary', 'Experience_Years']

==========================================
 5. DESCRIPTIVE STATISTICAL SUMMARY
==========================================

            EmpID        Salary  Experience_Years
count    6.000000      6.000000          6.000000
mean   103.500000  35166.666667          4.500000
std      1.870829   7467.708261          1.870829
min    101.000000  25000.000000          2.000000
25%    102.250000  30500.000000          3.250000
50%    103.500000  35000.000000          4.500000
75%    104.750000  40250.000000          5.750000
max    106.000000  45000.000000          7.000000