In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv('employee_salaries.csv')

print("==========================================")
print(" 1. FILTERING DATA (Salary > 35,000)      ")
print("==========================================")
high_salary_df = df[df['Salary'] > 35000]
display(high_salary_df)

print("\n==========================================")
print(" 2. MULTI-CONDITION FILTERING             ")
print(" (Salary >= 35000 AND Experience >= 5)    ")
print("==========================================")
filtered_df = df[(df['Salary'] >= 35000) & (df['Experience_Years'] >= 5)]
display(filtered_df)

print("\n==========================================")
print(" 3. SORTING DATA BY EXPERIENCE (DESCENDING)")
print("==========================================")
sorted_df = df.sort_values(by='Experience_Years', ascending=False)
display(sorted_df)

==========================================
 1. FILTERING DATA (Salary > 35,000)
==========================================

   EmpID     Name Department  Salary  Experience_Years
2    103    Divya        CSE   45000                 7
3    104    Priya      AI&DS   38000                 5
5    106  Karthik      AI&DS   41000                 6

==========================================
 2. MULTI-CONDITION FILTERING
 (Salary >= 35000 AND Experience >= 5)
==========================================

   EmpID     Name Department  Salary  Experience_Years
2    103    Divya        CSE   45000                 7
3    104    Priya      AI&DS   38000                 5
5    106  Karthik      AI&DS   41000                 6

==========================================
 3. SORTING DATA BY EXPERIENCE (DESCENDING)
==========================================

   EmpID     Name Department  Salary  Experience_Years
2    103    Divya        CSE   45000                 7
5    106  Karthik      AI&DS   41000                 6
3    104    Priya      AI&DS   38000                 5
4    105     Ravi         IT   32000                 4
1    102     Bala         IT   30000                 3
0    101     Arun         HR   25000                 2

In [2]:
# 1. Grouping by Department and calculating mean Salary & Experience
print("==========================================")
print(" 1. AVERAGE SALARY & EXPERIENCE BY DEPT   ")
print("==========================================")
dept_summary = df.groupby('Department')[['Salary', 'Experience_Years']].mean().reset_index()
display(dept_summary)

# 2. Advanced Aggregation (Count, Min, Max, Mean Salary by Department)
print("\n==========================================")
print(" 2. ADVANCED SALARY STATS BY DEPARTMENT   ")
print("==========================================")
dept_advanced = df.groupby('Department')['Salary'].agg(['count', 'min', 'max', 'mean']).reset_index()
display(dept_advanced)

# 3. Grouping by City
print("\n==========================================")
print(" 3. TOTAL SALARY EXPENSE BY CITY          ")
print("==========================================")
city_summary = df.groupby('City')['Salary'].sum().reset_index()
display(city_summary)

==========================================
 1. AVERAGE SALARY & EXPERIENCE BY DEPT
==========================================

  Department   Salary  Experience_Years
0      AI&DS  39500.0               5.5
1        CSE  45000.0               7.0
2         HR  25000.0               2.0
3         IT  31000.0               3.5

==========================================
 2. ADVANCED SALARY STATS BY DEPARTMENT
==========================================

  Department  count    min    max     mean
0      AI&DS      2  38000  41000  39500.0
1        CSE      1  45000  45000  45000.0
2         HR      1  25000  25000  25000.0
3         IT      2  30000  32000  31000.0

==========================================
 3. TOTAL SALARY EXPENSE BY CITY
==========================================

KeyError: 'City'